jenkinsci/code-coverage-api-plugin

src/main/java/io/jenkins/plugins/coverage/CoverageProcessor.java
src/test/java/io/jenkins/plugins/coverage/CoverageCornerCaseTest.java
src/test/java/io/jenkins/plugins/coverage/CoveragePublisherPipelineTest.java
src/test/java/io/jenkins/plugins/coverage/CoverageScriptedPipelineScriptBuilder.java

[JENKINS-51611] Add several tests

---

src/main/java/io/jenkins/plugins/coverage/targets/CoveragePaint.java

Just an example for https://issues.jenkins-ci.org/browse/JENKINS-51499

License update sample

---

src/main/java/io/jenkins/plugins/coverage/CoverageAction.java
src/main/java/io/jenkins/plugins/coverage/CoverageProjectAction.java
src/main/resources/io/jenkins/plugins/coverage/CoverageProjectAction/floatingBox.jelly
src/main/resources/io/jenkins/plugins/coverage/CoverageProjectAction/nodata.jelly
src/main/resources/io/jenkins/plugins/coverage/targets/CoverageResult/index.jelly
src/main/webapp/scripts/custom-chart.js

We now can see code coverage of the most recent build in the project page.

[JENKINS-52666] Show coverage at the project page.

---

CHANGELOG.md

I will update README and release plugin tomorrow.

add changelog for 1.0.0-rc-1 release

---

src/main/java/io/jenkins/plugins/coverage/targets/CoverageAggregationRule.java
src/main/resources/io/jenkins/plugins/coverage/adapter/jacoco-to-standard.xsl
src/main/webapp/scripts/custom-chart.js

- fix incorrect `conditionals` calculating for Jacoco.
- ratio `0/0` will be regard as no data before, now it will be view as missed.
- improve result page.

[JENKINS-53023] - Fix broken coverage calculating

---

src/main/java/io/jenkins/plugins/coverage/CoverageFeatureConstants.java
src/main/java/io/jenkins/plugins/coverage/CoverageProcessor.java
src/main/java/io/jenkins/plugins/coverage/adapter/CoverageReportAdapter.java
src/main/java/io/jenkins/plugins/coverage/adapter/parser/JavaCoverageParser.java
src/main/java/io/jenkins/plugins/coverage/source/DefaultSourceFileResolver.java
src/main/java/io/jenkins/plugins/coverage/source/SourceFileResolver.java
src/main/java/io/jenkins/plugins/coverage/targets/CoverageResult.java

Support additional property which can provide extra information for report to use.
Related issue: https://github.com/jenkinsci/code-coverage-api-plugin/issues/69

support source path property

---

src/main/java/io/jenkins/plugins/coverage/source/DefaultSourceFileResolver.java

Use 'FixedThreadPool' to create five thread to copy files.
See: https://github.com/jenkinsci/code-coverage-api-plugin/issues/77

Speed up copying source files

---

src/main/java/io/jenkins/plugins/coverage/targets/CoverageElementRegister.java

Fixes #84  @cizezsy  Please, take a look

fix repeated Global Thresholds elements

---

src/main/java/io/jenkins/plugins/coverage/source/DefaultSourceFileResolver.java

Source files will partially copied when using transient agent.
see: https://github.com/jenkinsci/code-coverage-api-plugin/issues/82

Use CountDownLatch to wait all copy taks completed.

---

src/main/java/io/jenkins/plugins/coverage/CoverageColumn.java
src/main/resources/io/jenkins/plugins/coverage/CoverageColumn/column.jelly
src/main/resources/io/jenkins/plugins/coverage/Messages.properties
src/main/resources/io/jenkins/plugins/coverage/Messages_zh_CN.properties

Add view column for coverage. 
See #79.

Feat: Support view column for coverage

---

src/main/java/io/jenkins/plugins/coverage/CoverageProcessor.java

Fix: NullPointerException when merge report between action

---

src/main/webapp/scripts/custom-chart.js

**changes:**
- optimize visual appearance

Chart: add space to report link

---

src/main/java/io/jenkins/plugins/coverage/CoverageAction.java
src/main/java/io/jenkins/plugins/coverage/CoverageProcessor.java
src/main/java/io/jenkins/plugins/coverage/threshold/Threshold.java

Fix: failed the build gracefully when coverage enforcement is failed

---

src/main/java/io/jenkins/plugins/coverage/CoverageProcessor.java
src/main/java/io/jenkins/plugins/coverage/CoveragePublisher.java
src/main/resources/io/jenkins/plugins/coverage/CoveragePublisher/config.jelly
src/main/resources/io/jenkins/plugins/coverage/CoveragePublisher/help-applyThresholdRecursively.html
src/main/resources/io/jenkins/plugins/coverage/CoveragePublisher/help-calculateDiffForChangeRequests.html
src/main/resources/io/jenkins/plugins/coverage/CoveragePublisher/help-failNoReports.html
src/main/resources/io/jenkins/plugins/coverage/CoveragePublisher/help-failUnhealthy.html
src/main/resources/io/jenkins/plugins/coverage/CoveragePublisher/help-failUnstable.html
src/test/java/io/jenkins/plugins/coverage/CoveragePublisherPipelineTest.java
src/test/java/io/jenkins/plugins/coverage/CoverageScriptedPipelineScriptBuilder.java

Feat: change the default apply strategy of threshold

---

pom.xml
src/main/java/io/jenkins/plugins/coverage/adapter/util/XMLUtils.java

Hello.
To support it we switch to Saxon HE which is an open source library
to work with xml which supports XSLT 2.0.
Thank you

Add support of XSLT 2.0

---

src/main/java/io/jenkins/plugins/coverage/CoverageProcessor.java
src/main/java/io/jenkins/plugins/coverage/CoveragePublisher.java
src/main/resources/io/jenkins/plugins/coverage/CoveragePublisher/config.jelly
src/main/resources/io/jenkins/plugins/coverage/CoveragePublisher/help-failBuildIfCoverageDecreasedInChangeRequest.html

Hi
This is how this looks:
Thank you.

Add the ability to fail builds in case if code coverage was decreased in a change request build

---

src/main/java/io/jenkins/plugins/coverage/CoverageProcessor.java

I'm trying to calculate coverage diffs, but it's not working. It's getting as far as finding the target branch, but I can't tell which of the many checks that follow are failing. So I've added log messages for each check.

Log more reasons a coverage diff isn't calculated

---

pom.xml
src/main/java/io/jenkins/plugins/coverage/CoverageChecksPublisher.java
src/main/java/io/jenkins/plugins/coverage/CoveragePublisher.java

Adds logging to the build log to help debug issues

Update to latest checks-api API

---

src/main/resources/io/jenkins/plugins/coverage/CoverageAction/summary.jelly

This is preparing for a fix to JENKINS-65033
this is backwards and forwards compatible

Use inline element in run summary next to icon

---

README.md
pom.xml
src/main/java/io/jenkins/plugins/coverage/CoverageProcessor.java

integrate forensics-api to search for reference build 
preparation for #190

integrate forensics-api for reference build search

---

plugin/src/main/java/io/jenkins/plugins/coverage/model/CoverageReporter.java
plugin/src/main/java/io/jenkins/plugins/coverage/model/FileChangesProcessor.java
plugin/src/test/java/io/jenkins/plugins/coverage/model/FileChangesProcessorTest.java
plugin/src/test/resources/io/jenkins/plugins/coverage/model/file-changes-test-before.xml

I added the support for calculating the file coverage delta for renamed files.

Support renames for calculating the file coverage delta

---

plugin/pom.xml
plugin/src/test/java/io/jenkins/plugins/coverage/metrics/source/SourceCodeITest.java

See https://github.com/jenkinsci/code-coverage-api-plugin/issues/677

Add a test case to expose #677 (absolute workspace path rejected)

---

plugin/doc/dependency-graph.puml
plugin/pom.xml
plugin/src/main/java/io/jenkins/plugins/coverage/metrics/steps/CoverageMetricColumn.java
plugin/src/test/java/io/jenkins/plugins/coverage/metrics/steps/CoverageMetricColumnTest.java

See [JENKINS-70981](https://issues.jenkins.io/browse/JENKINS-70981) for details.

[JENKINS-70981] Remove configure permission when querying enums
