src/main/java/io/jenkins/plugins/coverage/targets/CoverageResult.java, src/main/resources/io/jenkins/plugins/coverage/targets/CoverageResult/index.jelly, src/main/webapp/scripts/custom-chart.js
Data range handler now can filter coverage item, and it will reduce the number of coverage shown on the page.
**For example**, if we set range to [0, 100], it will show 20 items:
If we set range to [0, 66], it will only show 4 items:
The default range is set to [0, 75].
=>  [JENKINS-51609] Filter report to show only low coverage code

src/main/java/io/jenkins/plugins/coverage/targets/Chartable.java, src/main/java/io/jenkins/plugins/coverage/targets/CoverageAggregationMode.java, src/main/java/io/jenkins/plugins/coverage/targets/CoverageAggregationRule.java, src/main/java/io/jenkins/plugins/coverage/targets/CoverageChart.java, src/main/java/io/jenkins/plugins/coverage/targets/CoverageElement.java, src/main/java/io/jenkins/plugins/coverage/targets/CoverageMetric.java, src/main/java/io/jenkins/plugins/coverage/targets/CoveragePaint.java, src/main/java/io/jenkins/plugins/coverage/targets/CoveragePaintRule.java, src/main/java/io/jenkins/plugins/coverage/targets/CoverageResult.java, src/main/java/io/jenkins/plugins/coverage/targets/CoverageTree.java, src/main/java/io/jenkins/plugins/coverage/targets/CoverageTreeElement.java, src/main/java/io/jenkins/plugins/coverage/targets/HasName.java, src/main/java/io/jenkins/plugins/coverage/targets/Ratio.java
update the copyright holders according to the file contributors show in GitHub and @author annotation.
=> [JENKINS-51499] Clean-up Licensenes in the adopted code

src/main/java/io/jenkins/plugins/coverage/adapter/JacocoReportAdapter.java, src/main/java/io/jenkins/plugins/coverage/adapter/JavaCoverageReportAdapterDescriptor.java, src/main/java/io/jenkins/plugins/coverage/adapter/parser/CoverageParser.java, src/main/java/io/jenkins/plugins/coverage/targets/CoverageAggregationRule.java, src/main/java/io/jenkins/plugins/coverage/targets/CoverageResult.java, src/main/resources/io/jenkins/plugins/coverage/adapter/jacoco-to-standard.xsl
background: https://github.com/jenkinsci/code-coverage-api-plugin/issues/44
Add `attr-mode` which will read line coverage from attribute instead of child line elements.
=> [JENKINS-53130] Code coverage 0% in jenkins with Jacoco

src/main/java/io/jenkins/plugins/coverage/CoverageProcessor.java
In case of multiple coverage files, the plugin tries to copy them to /jacoco1 where it usually does not have any access. Generating the names of the additional files (with number appended) in the same way as the original file name fixed it for me. Then I at least get a working summary of all coverages.
Keep up the good work with the plugin, we really need a new, flexible coverage plugin for Jenkins.
=> Fixed support for multiple coverage files

README.md
Please excuse me for pedantism, but the correct official spelling of project name is `JaCoCo` - it was formed as acronym from "**Ja**va **Co**de **Co**verage" :wink:
BTW nice integration! :thumbsup: We plan to mention it in JaCoCo documentation - jacoco/jacoco#762
=> Fix spelling: "Jacoco" => "JaCoCo"

.gitignore, pom.xml, src/main/java/io/jenkins/plugins/coverage/CoverageProcessor.java, src/main/java/io/jenkins/plugins/coverage/CoveragePublisher.java, src/main/java/io/jenkins/plugins/coverage/targets/CoverageResult.java, src/main/resources/io/jenkins/plugins/coverage/CoverageAction/summary.jelly, src/main/resources/io/jenkins/plugins/coverage/CoverageProjectAction/floatingBox.jelly, src/main/resources/io/jenkins/plugins/coverage/CoveragePublisher/config.jelly, src/main/resources/io/jenkins/plugins/coverage/targets/CoverageResult/index.jelly
It would be very convenient to see the code coverage diff right in Jenkins. If our
build is going for a multibranch change request job  - we take the
target branch commit that is used for our change request build. Then, we search through the
last fixed amount of builds the build that was built for this target branch commit. If
we find it - we check if it has line code coverage information. In case it has it -  we calculate diff between the current code coverage and this target branch build coverage.
Examples:
Increased code coverage:
Decreased code coverage:
No changes:
Thank you.
=> Show diff in coverage for change request builds

src/main/webapp/scripts/custom-chart.js
Hi.
In large projects you have a lot of code lines and a lot of tests for
them. So, you may even delete whole tests and your code coverage won't
decrease if you track it in integer. It's more convenient if your
code coverage is shown in float so you can easily detect any code
coverage change between builds using the trend between builds that
Code Coverage Api plugin provides.
Thank you.
=> Change code coverage trend to use float format for coverage percentage

README.md
Add "Merging Reports" to README.md
- Added a very useful example from https://github.com/jenkinsci/code-coverage-api-plugin/issues/111#issuecomment-519849515 which shows how to combine multiple reports (*.xml files) into one report.
- Removed a redundant "REST API" from subsection "REST API"
=> Add "Merging Reports" to README.md

src/main/webapp/scripts/custom-chart.js
Hi.
In case if your code coverage result has some long name It may overlap with the chart legend.
Before:
After:
What do you think about this?
Thank you.
=> Fix overlapping in case a coverage result has some really long name

src/main/java/io/jenkins/plugins/coverage/source/DefaultSourceFileResolver.java
We see unbounded thread growth with the following stack trace:
```
java.lang.Throwable: created pool #47
at java.util.concurrent.Executors$DefaultThreadFactory.<init>(Executors.java:610)
at java.util.concurrent.Executors.defaultThreadFactory(Executors.java:353)
at java.util.concurrent.ThreadPoolExecutor.<init>(ThreadPoolExecutor.java:1203)
at java.util.concurrent.Executors.newFixedThreadPool(Executors.java:89)
at io.jenkins.plugins.coverage.source.DefaultSourceFileResolver.resolveSourceFiles(DefaultSourceFileResolver.java:83)
at io.jenkins.plugins.coverage.CoverageProcessor.performCoverageReport(CoverageProcessor.java:115)
at io.jenkins.plugins.coverage.CoveragePublisher.perform(CoveragePublisher.java:94)
at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:80)
at …
```
=> Avoid thread leak by copying files synchronously

src/main/java/io/jenkins/plugins/coverage/source/DefaultSourceFileResolver.java, src/main/resources/io/jenkins/plugins/coverage/targets/CoverageResult/index.jelly
The HTML generated with painted source code has a bunch of errors with tags that may make the rendering bad on older browsers or may anyhow leave to the browser the freedom to rearrange the code.
Example from Firefox source code parsing:
In the example you see that the closing of `<a>` is considered invalid (it is not a _void element_) and the `<td>` of hits is never closed. Also the whole table was inside a `<pre>` (preformatted) tag which doesn't make sense it being a table.
This PR fixes this little HTML quirks and makes the page more HTML5 compliant.
=> Fix small HTML tags errors in painted source code files

src/main/java/io/jenkins/plugins/coverage/CoverageProjectAction.java
When calculating the link to last coverage data, which is the link from the left menu, the plugin would just consider builds that were SUCCESS. But the plugin itself can make a build UNSTABLE (ie. code coverage limits not reached) and that data will not be pointed therefore.
This PR just takes into account both SUCCESS and UNSTABLE results for the link.
To reproduce:
-) Set code coverage thresholds (unstableThreshold) to a value that your code is not reaching and execute the build.
-) Check the link from the left menu in "Coverage Report": this will not point to the just executed job. As an extreme if all are UNSTABLE then the menu action will fail.
Tested PR manually with success.
=> When calculating link to last coverage data consider both SUCCESS or UNSTABLE

src/main/java/io/jenkins/plugins/coverage/source/DefaultSourceFileResolver.java, src/main/java/io/jenkins/plugins/coverage/targets/CoverageResult.java, src/test/java/io/jenkins/plugins/coverage/CoveragePublisherPipelineTest.java, src/test/java/io/jenkins/plugins/coverage/CoverageScriptedPipelineScriptBuilder.java
- Fix #90.
- Rendering source file in agent.
=> Improve source file resolving

src/main/webapp/scripts/custom-chart.js
Before this change, this api plugin would display "&lt;init&gt;" method as "&amp;amp;lt;init&amp;amp;gt;" when showing coverage report for the method.
Generally, this bug occurs when the method name contains "&lt;" and/or "&gt;". Let's still take "&lt;init&gt;" for example, after the process of `io.jenkins.plugins.coverage.targets.CoverageResult#xmlTransform`, this name will be "&amp;lt;init&amp;gt;", then since the corresponding jelly file's `escape-by-default` property is true, the name will be further escaped to "&amp;amp;lt;init&amp;amp;gt;".
When displaying the method name, the text is displayed "as is", so escaping is not necessary. So this PR won't lead to XSS issues.
After this change, the display will work fine.
=> display name contains "<" and/or ">" (<init> for example) normally

src/main/java/io/jenkins/plugins/coverage/targets/CoverageResult.java, src/main/resources/io/jenkins/plugins/coverage/targets/CoverageResult/index.jelly
Before this pr, the plugin shows coverage reports like this:
Now the issue is fixed!
=> JENKINS-60359: Use standard breadcrumbs

src/main/java/io/jenkins/plugins/coverage/source/DefaultSourceFileResolver.java
The Jacoco fix in 4081720909b brought new code that tries to find the
source file in case other ways didn't work. To do this it creates a
map of file names to look for. And it logs warnings in case of any
duplicates. Becase there may be a lot of them a log would quite apace,
we remove the warnings.
=> Fix #150. Remove wars about source files with the same names

src/main/java/io/jenkins/plugins/coverage/CoverageProcessor.java
=> Also set a fail message if marking stage as unstable so that checks API correctly reports non-success

pom.xml, src/main/webapp/scripts/custom-chart.js
Everything except for source code looks fine now from what I can tell
=> Add theme support

src/main/java/io/jenkins/plugins/coverage/adapter/converter/DocumentConverter.java
Fix for Issue: https://github.com/jenkinsci/code-coverage-api-plugin/issues/162
In our environment, we noticed that Cobertura files were failing consumption.  The error was traced to Cobertura itself adding a doctype to the top of it's files.  
From commit 0a43672:
"Per OWASP (https://cheatsheetseries.owasp.org/cheatsheets/XML_External_Entity_Prevention_Cheat_Sheet.html#jaxp-documentbuilderfactory-saxparserfactory-and-dom4j), not all four features need set at the same time.
If "disallow-doctype-decl" cannot be set to false, in this case because Cobertura sets the DOCTYPE, then at least "external-general-entities" should be set to false.
Both do not need to be set as "disallow-doctype-decl" is already a more secure setting, making setting "external-general-entities" worthless."
=> Ignore Doctype errors caused by Cobertura adding to top of xml files.

pom.xml
Preparation for #182 and #195 
* Bump Jenkins baseline version to 2.249
* Clean up pom 
* Outsourced dependency version to <properties> tag
* Sort dependencies
=> bump jenkins baseline to 2.249

src/main/java/io/jenkins/plugins/coverage/CoverageChecksPublisher.java, src/main/java/io/jenkins/plugins/coverage/CoverageProcessor.java, src/main/java/io/jenkins/plugins/coverage/targets/CoverageResult.java, src/main/resources/io/jenkins/plugins/coverage/CoverageAction/summary.jelly, src/main/resources/io/jenkins/plugins/coverage/CoverageProjectAction/floatingBox.jelly, src/main/resources/io/jenkins/plugins/coverage/targets/CoverageResult/index.jelly, src/test/java/io/jenkins/plugins/coverage/CoverageChecksPublisherTest.java
For now only the line coverage is calculating as diff, if `calculateDiffForChangeRequests` is enabled and a target branch is found.
* Extended  the diff coverage api by all existing coverage elements of target branch. 
* make variables names more meaningful: 
1. `changeRequestCoverageDiffWithTargetBranch` does not exist anymore and is part of the deltaResult map now. The getter, which is used until now `getChangeRequestCoverageDiffWithTargetBranch` is replaced by `getLineCoverageDelta()`, which extracts the corresponding metric from the deltaResults map. Therefore other plugins are able to use all delta metrics.
2. `linkToBuildThatWasUsedForComparison`is now the `referenceBuildUrl`
I'm not sure if this is all working as expected or if I'm breaking the api with it.. So can this please be …
=> Extend delta coverage api

src/main/java/io/jenkins/plugins/coverage/CoverageChecksPublisher.java, src/test/java/io/jenkins/plugins/coverage/CoverageChecksPublisherTest.java
Followup to #198: Show delta of line **and** branch coverage with respect to target branch in GitHub checks.
=> Use new delta values for branch coverage in checks title

src/main/java/io/jenkins/plugins/coverage/model/CoverageNode.java, src/test/java/io/jenkins/plugins/coverage/model/CoverageNodeTest.java
- If the package name contains a single dot, then splitting broke with an exception.
- If the module node does not contain packages, then the next sub nodes have been split.
- If the package name does not contain dots, then the package was deleted.
Fixes #223.
=> Fix `splitPackages` for some corner cases

pom.xml, src/main/java/io/jenkins/plugins/coverage/model/CoverageTrendChart.java, src/test/java/io/jenkins/plugins/coverage/model/CoverageJobActionTest.java
The actual fix is done in the upstream module. This PR just adds a test to expose the issues
- https://github.com/jenkinsci/code-coverage-api-plugin/issues/227
- https://github.com/jenkinsci/code-coverage-api-plugin/issues/231
See https://github.com/jenkinsci/plugin-util-api-plugin/pull/133
=> Add test case to expose issues #227 and #231

src/main/java/io/jenkins/plugins/coverage/model/CoverageBuildAction.java, src/main/resources/io/jenkins/plugins/coverage/CoveragePullRequestMonitoringPortlet/monitor.jelly, src/main/resources/io/jenkins/plugins/coverage/model/CoverageViewModel/index.jelly
This fixes a bug when Jenkins is not running with the default prefix, see
https://github.com/jenkinsci/code-coverage-api-plugin/issues/242 for details.
=> Use `${resURL}` rather than `${rootURL}` when resolving JS files

src/main/java/io/jenkins/plugins/coverage/detector/AntPathReportDetector.java, src/main/java/io/jenkins/plugins/coverage/source/DefaultSourceFileResolver.java, src/test/java/io/jenkins/plugins/coverage/BlockSlaveToMasterFileCallable.java, src/test/java/io/jenkins/plugins/coverage/CoveragePublisherPipelineTest.java, src/test/java/io/jenkins/plugins/coverage/CoverageScriptedPipelineScriptBuilder.java
Compatible with https://github.com/jenkinsci/jenkins/pull/5885. See https://github.com/jenkinsci/remoting-security-workaround-plugin/blob/main/README.adoc#affected-functionality.
=> Remove agent-to-controller calls

src/main/java/io/jenkins/plugins/coverage/model/CoverageBuildAction.java, src/main/java/io/jenkins/plugins/coverage/model/CoverageViewModel.java, src/test/java/io/jenkins/plugins/coverage/model/CoverageBuildActionTest.java, src/test/java/io/jenkins/plugins/coverage/model/CoverageViewModelTest.java
Add unit tests that show the navigation to the source code view.
Starting with a `CoverageBuildAction` instance, one can navigate to the model of the source code view using the following code snippet:
```
SourceViewModel model = action.getTarget().getDynamic(link, null, null);
```
=> Add unit tests that show how to verify the source code view model

pom.xml, src/main/java/io/jenkins/plugins/coverage/CoverageProcessor.java, src/main/java/io/jenkins/plugins/coverage/model/Coverage.java, src/main/java/io/jenkins/plugins/coverage/model/CoverageBuildAction.java, src/main/java/io/jenkins/plugins/coverage/model/CoverageLeaf.java, src/main/java/io/jenkins/plugins/coverage/model/CoverageMetric.java, src/main/java/io/jenkins/plugins/coverage/model/CoverageNode.java, src/main/java/io/jenkins/plugins/coverage/model/CoverageSeriesBuilder.java, src/main/java/io/jenkins/plugins/coverage/model/CoverageViewModel.java, src/main/java/io/jenkins/plugins/coverage/model/SourceViewModel.java, src/main/java/io/jenkins/plugins/coverage/model/TreeMapNodeConverter.java, src/main/resources/io/jenkins/plugins/coverage/model/CoverageBuildAction/summary.jelly, src/main/resources/io/jenkins/plugins/coverage/model/Messages.properties, src/test/java/io/jenkins/plugins/coverage/model/CoverageBuildActionTest.java, src/test/java/io/jenkins/plugins/coverage/model/CoverageLeafTest.java, src/test/java/io/jenkins/plugins/coverage/model/CoverageNodeTest.java, src/test/java/io/jenkins/plugins/coverage/model/CoverageTest.java
- Use the locale of the browser when formatting percentages.
- Use `Fraction` instances when computing coverages.
- Use `Fraction` instances when computing deltas.
Required to get #289 running on a machine with a non-US locale in Jenkins (e.g. German).
=> Improve precision and formatting of percentages

plugin/src/main/java/io/jenkins/plugins/coverage/CoverageAction.java, plugin/src/main/java/io/jenkins/plugins/coverage/CoverageProcessor.java
When `failBuildIfCoverageDecreasedInChangeRequest` is set, as well as failing the build by throwing the exeception this PR adds a failMessage to the action to ensure that when the check is published it is marked as failed.
Fixes #256
=> If the coverage decreases on a PR, mark the check as failed

plugin/src/main/java/io/jenkins/plugins/coverage/model/CoverageNode.java, plugin/src/main/java/io/jenkins/plugins/coverage/model/CoveragePercentage.java, plugin/src/main/java/io/jenkins/plugins/coverage/model/SafeFraction.java, plugin/src/test/java/io/jenkins/plugins/coverage/model/CoveragePercentageTest.java, plugin/src/test/java/io/jenkins/plugins/coverage/model/SafeFractionTest.java
Otherwise the `Fraction` class will produce an overflow and throws an `ArithmeticException`.
=> Introduce a `SafeFraction` that carefully handles operations on `Fraction` instances

plugin/src/main/java/io/jenkins/plugins/coverage/adapter/CoberturaReportAdapter.java
Allows for this report adapter to be disambiguated from the one provided by the Cobertura plugin in the case both plugins are installed; see https://stackoverflow.com/a/72839475/466874 for this specific case and https://issues.jenkins.io/browse/INFRA-2012 and https://github.com/jenkins-infra/helpdesk/issues/1662 for the fundamental issue.
=> Add a coberturaReportAdapter symbol to disambiguate from Cobertura plugin's symbols

plugin/pom.xml, plugin/src/main/java/io/jenkins/plugins/coverage/model/CoverageBuildAction.java, plugin/src/main/java/io/jenkins/plugins/coverage/model/CoverageReporter.java, plugin/src/test/java/io/jenkins/plugins/coverage/CoverageChecksPublisherTest.java, plugin/src/test/java/io/jenkins/plugins/coverage/model/AbstractCoverageTest.java, plugin/src/test/java/io/jenkins/plugins/coverage/model/CoverageBuildActionTest.java, plugin/src/test/java/io/jenkins/plugins/coverage/model/CoverageNodeTest.java, plugin/src/test/java/io/jenkins/plugins/coverage/model/CoverageTest.java, plugin/src/test/java/io/jenkins/plugins/coverage/model/visualization/dashboard/CoverageColumnTest.java
Otherwise, the whole coverage result XML will be loaded just for a single value.
Will fix jenkins-infra/helpdesk#3029.
=> Use the coverages that are persisted within the action if possible

plugin/src/main/java/io/jenkins/plugins/coverage/model/visualization/dashboard/ChangeCoverage.java, plugin/src/main/java/io/jenkins/plugins/coverage/model/visualization/dashboard/ChangeCoverageDelta.java, plugin/src/main/java/io/jenkins/plugins/coverage/model/visualization/dashboard/CoverageColumn.java, plugin/src/main/java/io/jenkins/plugins/coverage/model/visualization/dashboard/CoverageColumnType.java, plugin/src/main/java/io/jenkins/plugins/coverage/model/visualization/dashboard/IndirectCoverageChanges.java, plugin/src/main/resources/io/jenkins/plugins/coverage/model/CoverageBuildAction/summary.jelly, plugin/src/test/java/io/jenkins/plugins/coverage/model/testutil/CoverageStubs.java, plugin/src/test/java/io/jenkins/plugins/coverage/model/visualization/dashboard/ChangeCoverageDeltaTest.java, plugin/src/test/java/io/jenkins/plugins/coverage/model/visualization/dashboard/ChangeCoverageTest.java, plugin/src/test/java/io/jenkins/plugins/coverage/model/visualization/dashboard/CoverageColumnTest.java, plugin/src/test/java/io/jenkins/plugins/coverage/model/visualization/dashboard/IndirectCoverageChangesTest.java, plugin/src/test/java/io/jenkins/plugins/coverage/model/visualization/dashboard/ProjectCoverageDeltaTest.java, plugin/src/test/java/io/jenkins/plugins/coverage/model/visualization/dashboard/ProjectCoverageTest.java
The URL anchors of links in the dashboard column and in the build overview have been fixed. These URLs are now pointing to the corresponding coverage report view in order to simplify the navigation.
=> Fix coverage URL anchors

plugin/src/main/java/io/jenkins/plugins/coverage/model/visualization/code/SourceCodeFacade.java, plugin/src/test/java/io/jenkins/plugins/coverage/model/CoveragePluginSourceITest.java
Fix for issue #441:
Folders and files which are temporary created while painting the source code are removed after usage now.
I also added an additional assertion to verify that the created temporary directories and only these are deleted.
=> [#441] Delete temporary folders on agent after coloring source code files

plugin/src/main/java/io/jenkins/plugins/coverage/model/CoverageNode.java, plugin/src/main/java/io/jenkins/plugins/coverage/model/CoverageReporter.java, plugin/src/main/java/io/jenkins/plugins/coverage/model/CoverageTableModel.java, plugin/src/main/java/io/jenkins/plugins/coverage/model/FilePathValidator.java, plugin/src/test/java/io/jenkins/plugins/coverage/model/CoverageNodeTest.java, plugin/src/test/java/io/jenkins/plugins/coverage/model/CoveragePluginSourceITest.java, plugin/src/test/java/io/jenkins/plugins/coverage/model/FileChangesProcessorTest.java, plugin/src/test/java/io/jenkins/plugins/coverage/model/FilePathValidatorTest.java
Fixes issue #433:
I inserted a validation of the file structure.
`FileCoverageNodes` which have the same package and file name are removed from the coverage report since at the moment, these files cannot be handled correctly.
These cases will be logged including the name of the affected files.
This can be used as a workaround for the moment to prevent exceptions.
To also cover reference builds, this is executed for the current and the reference coverage tree.
I chose the option to delete ambiguous nodes afterwards, since it also relates to the reference trees, which belongs to older builds, where duplicate paths are also possible at the moment.
And even if I would simply not add files with duplicate paths when creating the tree, there is a possibility that the coverage tree contains empty …
=> [#433] Remove duplicate file nodes 

plugin/src/test/java/io/jenkins/plugins/coverage/model/AbstractCoverageTest.java, plugin/src/test/java/io/jenkins/plugins/coverage/model/CoverageNodeTest.java, plugin/src/test/resources/io/jenkins/plugins/coverage/model/cobertura-npe.xml
Seems that our parser already handles that file correctly.
See https://github.com/jenkinsci/code-coverage-api-plugin/issues/473
=> Try to expose NPE with Cobertura parser in #473

plugin/src/main/java/io/jenkins/plugins/coverage/model/CodeDeltaCalculator.java, plugin/src/main/java/io/jenkins/plugins/coverage/model/FileChangesProcessor.java, plugin/src/test/java/io/jenkins/plugins/coverage/model/CodeDeltaCalculatorTest.java, plugin/src/test/java/io/jenkins/plugins/coverage/model/FileChangesProcessorTest.java
Fix for issue #487 .
Missing reference files will be ignored when processing the coverage deltas.
Ignored files are logged.
I also added tests to ensure the fix worked.
=> #487 - Skip missing reference files when creating coverage delta

plugin/src/main/java/io/jenkins/plugins/coverage/model/CodeDeltaCalculator.java, plugin/src/test/java/io/jenkins/plugins/coverage/model/CodeDeltaCalculatorTest.java
I added an additional check to prevent exception in case of mismatches between the calculated code delta and the Jacoco coverage data.
This prevents the bug from issue #467.
After an unexpected behavior has been detected, all caluclations based on the code delta are skipped and the error is logged.
=> Prevent mismatches between code delta and jacoco data - Issue #467

plugin/src/main/java/io/jenkins/plugins/coverage/CoverageChecksPublisher.java, plugin/src/main/java/io/jenkins/plugins/coverage/CoveragePublisher.java, plugin/src/main/resources/io/jenkins/plugins/coverage/CoveragePublisher/config.jelly, plugin/src/main/resources/io/jenkins/plugins/coverage/CoveragePublisher/help-checksName.html, plugin/src/test/java/io/jenkins/plugins/coverage/CoverageChecksPublisherTest.java, plugin/src/test/java/io/jenkins/plugins/coverage/model/ChecksNameITest.java, ui-tests/src/main/java/io/jenkins/plugins/coverage/CoveragePublisher/CoveragePublisher.java
This fulfills issue https://github.com/jenkinsci/code-coverage-api-plugin/issues/204
Adds a new parameter to the plugin called `checksName` in order to provide a custom checks name to the SCM provider. Will default back to `Code Coverage` if no `checksName` is provided to ensure compatibility isn't broken.
This feature is similar to the one merged into `junit-plugin` https://github.com/jenkinsci/junit-plugin/pull/211.
=> [#204] - Add SCM `checksName` parameter

plugin/src/main/java/io/jenkins/plugins/coverage/CoveragePublisher.java
Fixes #522.
The checks name needs to be set during deserialization of old freestyle job configurations of version 3.2 and lower.
=> Restore missing checks name during deserialization

plugin/src/main/java/io/jenkins/plugins/coverage/CoverageProcessor.java, plugin/src/test/java/io/jenkins/plugins/coverage/CoverageProcessorTest.java
While calculating difference in coverage, there might be a difference even without code change, due to floating point rounding errors. Converting the diff float to BigDecimal with appropriate scale and converting back solves this issue.
Fixes: https://github.com/jenkinsci/code-coverage-api-plugin/issues/191
=> Fix float precision issue in coverage diff 

plugin/src/main/java/io/jenkins/plugins/coverage/model/CoverageNode.java, plugin/src/test/java/io/jenkins/plugins/coverage/model/CoverageNodeTest.java, plugin/src/test/resources/io/jenkins/plugins/coverage/model/cobertura-package-root.xml
When a coverage node has been created from a cobertura report, the `mergePath` method was returning a wrong path if the provided local path contains any subpaths in it. Those subpaths were prepended to the local path thus doubling them in the merged path (for instance `"a/b/c"` was transformed to `"a/b/a/b/c"`).
As a consequence, `FileCoverageNode.getPath` was returning a wrong file path which prevented any source file painting and display in the Jenkins UI.
Fixes #456.
For the record, I deployed that fix to the Jenkins instance we are using in our development team and [source file coverage display](https://jenkins.softwareheritage.org/job/DVAU/job/gitlab-builds/6/coverage/) is now working when using cobertura reports. 
The fix seems pretty harmless to me, surely not the best one but I …
=> CoverageNode: Fix mergePath for node created from cobertura report

plugin/src/main/java/io/jenkins/plugins/coverage/metrics/steps/CoverageQualityGateEvaluator.java, plugin/src/test/java/io/jenkins/plugins/coverage/metrics/AbstractCoverageTest.java, plugin/src/test/java/io/jenkins/plugins/coverage/metrics/steps/CoverageQualityGateEvaluatorTest.java
When a value does not exist (because the reference build is not available, or there are no code changes), then the quality gate evaluation should be skipped.
Fixes https://github.com/jenkinsci/code-coverage-api-plugin/issues/579.
=> Ignore quality gates if the actual value does not exist

plugin/src/main/java/io/jenkins/plugins/coverage/metrics/model/ElementFormatter.java, plugin/src/main/java/io/jenkins/plugins/coverage/metrics/steps/CoverageBuildAction.java, plugin/src/main/java/io/jenkins/plugins/coverage/metrics/steps/CoverageChecksPublisher.java, plugin/src/main/java/io/jenkins/plugins/coverage/metrics/steps/CoverageViewModel.java, plugin/src/main/resources/coverage/coverage-summary.jelly, plugin/src/test/java/io/jenkins/plugins/coverage/metrics/AbstractCoverageTest.java, plugin/src/test/java/io/jenkins/plugins/coverage/metrics/charts/TreeMapNodeConverterTest.java, plugin/src/test/java/io/jenkins/plugins/coverage/metrics/steps/CoverageChecksPublisherTest.java, plugin/src/test/resources/io/jenkins/plugins/coverage/metrics/steps/coverage-publisher-summary.checks-expected-result, ui-tests/pom.xml
Currently, there are too many assumptions about the existing values. We need to add some guards to improve the title so that only meaningful results are actually produces. 
- When there are modified lines, print coverages of those lines. Otherwise, fall back to project coverage.
Will close #580.
=> Improve checks title and content

plugin/src/main/java/io/jenkins/plugins/coverage/metrics/steps/CoverageChecksPublisher.java, plugin/src/test/java/io/jenkins/plugins/coverage/metrics/steps/CoverageChecksPublisherTest.java
The title should be as short as possible. In the details we will see how the individual elements are composed of.
=> Do not show details in title, just the percentages

plugin/src/main/java/io/jenkins/plugins/coverage/metrics/model/ElementFormatter.java, plugin/src/main/java/io/jenkins/plugins/coverage/metrics/steps/CoverageBuildAction.java, plugin/src/main/java/io/jenkins/plugins/coverage/metrics/steps/CoverageChecksPublisher.java, plugin/src/main/java/io/jenkins/plugins/coverage/metrics/steps/CoverageViewModel.java, plugin/src/main/resources/io/jenkins/plugins/coverage/metrics/steps/Messages.properties, plugin/src/test/java/io/jenkins/plugins/coverage/metrics/steps/CoverageChecksPublisherTest.java, plugin/src/test/java/io/jenkins/plugins/coverage/metrics/steps/CoverageQualityGateEvaluatorTest.java, plugin/src/test/resources/io/jenkins/plugins/coverage/metrics/steps/coverage-publisher-details.checks-expected-result, plugin/src/test/resources/io/jenkins/plugins/coverage/metrics/steps/coverage-publisher-quality-gate.checks-expected-result, plugin/src/test/resources/io/jenkins/plugins/coverage/metrics/steps/coverage-publisher-summary.checks-expected-result
Add details about the covered and missed lines.
=> Improve summary checks message

plugin/pom.xml
Fixes https://github.com/jenkinsci/code-coverage-api-plugin/issues/630.
Release notes:
https://github.com/jenkinsci/coverage-model/releases/tag/v0.22.1
=> Bump version of coverage-model to 0.22.1

plugin/pom.xml, plugin/src/main/java/io/jenkins/plugins/coverage/metrics/model/ElementFormatter.java, plugin/src/test/java/io/jenkins/plugins/coverage/metrics/model/ElementFormatterTest.java
Fixes https://github.com/jenkinsci/code-coverage-api-plugin/issues/637.
=> Handle overflow in fractional numbers gracefully

plugin/src/main/java/io/jenkins/plugins/coverage/metrics/steps/CoverageRecorder.java, plugin/src/main/java/io/jenkins/plugins/coverage/metrics/steps/CoverageReporter.java
Otherwise not all paths will be converted to absolute paths.
=> Move resolving of paths to the beginning of the recorder

plugin/src/main/java/io/jenkins/plugins/coverage/metrics/steps/CoverageBuildAction.java
See https://github.com/jenkinsci/code-coverage-api-plugin/issues/647
=> Provide a fallback if the serialization is broken

plugin/src/main/java/io/jenkins/plugins/coverage/metrics/steps/CoverageChecksPublisher.java, plugin/src/main/java/io/jenkins/plugins/coverage/metrics/steps/PathResolver.java, plugin/src/test/java/io/jenkins/plugins/coverage/metrics/steps/CoverageChecksPublisherTest.java, plugin/src/test/resources/io/jenkins/plugins/coverage/metrics/steps/coverage-publisher-details.checks-expected-result
Fixes https://github.com/jenkinsci/code-coverage-api-plugin/issues/662
=> Do not show an icon in checks report when the coverage did not change

plugin/src/main/java/io/jenkins/plugins/coverage/metrics/steps/CoverageBuildAction.java, plugin/src/main/java/io/jenkins/plugins/coverage/metrics/steps/CoverageReporter.java, plugin/src/test/java/io/jenkins/plugins/coverage/metrics/steps/DeltaComputationITest.java
A reference build might contain different coverage actions with different IDs. When computing the delta, we need to select the action with the same ID to make the results comparable.
Example from PR #670 that did not change any code. The mutation coverage is compared with the code coverage 🐛
=> Use the correct ID of the action when comparing with reference build

README.md, plugin/src/main/resources/io/jenkins/plugins/coverage/metrics/steps/CoverageRecorder/help-sourceCodeRetention.html, plugin/src/main/resources/io/jenkins/plugins/coverage/metrics/steps/CoverageStep/help-sourceCodeRetention.html
=> Improve documentation for reference builds and source folders

plugin/src/main/resources/coverage/coverage-table.jelly, plugin/src/main/resources/coverage/coverage-table.properties, plugin/src/main/resources/io/jenkins/plugins/coverage/metrics/steps/CoverageViewModel/index.jelly, plugin/src/main/resources/io/jenkins/plugins/coverage/metrics/steps/CoverageViewModel/index.properties, plugin/src/main/webapp/js/view-model.js
On small displays the tab names are too long.
=> Shorten the names of the tabs

plugin/src/main/resources/io/jenkins/plugins/coverage/metrics/steps/CoverageRecorder/help-sourceDirectories.html, plugin/src/main/resources/io/jenkins/plugins/coverage/metrics/steps/CoverageStep/help-sourceDirectories.html
Followup for https://github.com/jenkinsci/prism-api-plugin/pull/101.
=> Add documentation for glob and regex syntaxes

plugin/pom.xml
The correct version of ECharts is now part of the BOM.
=> Use BOM version for ECharts

README.md, plugin/pom.xml, plugin/src/main/java/io/jenkins/plugins/coverage/metrics/steps/CoverageTokenMacro.java, plugin/src/test/java/io/jenkins/plugins/coverage/metrics/steps/CoverageTokenMacroITest.java, plugin/src/test/java/io/jenkins/plugins/coverage/metrics/steps/CoverageTokenMacroTest.java
=> Add token macro to extract all values of the `CoverageStatistics`

plugin/src/main/java/io/jenkins/plugins/coverage/metrics/steps/CoverageQualityGateEvaluator.java, plugin/src/test/java/io/jenkins/plugins/coverage/metrics/steps/CoverageQualityGateEvaluatorTest.java
Delta values are internally stored as fractions, but a user expects them as percentages when they are displayed or used in thresholds. So values in the range [-1, 1] should be converted to percentages in the range [-100%, 100%] before passed to the quality gate evaluation.
Fixes https://github.com/jenkinsci/code-coverage-api-plugin/issues/689
=> Convert delta fractions to percentages when used in quality gates

plugin/src/main/webapp/js/view-model.js
When the users (or the system) changes from dark to light mode (or the other way round), then the charts need to be re-rendered to use the correct background and foreground colors.
=> Redraw the trend charts when user changes color theme (dark/light mode)

plugin/pom.xml, plugin/src/main/java/io/jenkins/plugins/coverage/metrics/steps/CoverageChecksPublisher.java, plugin/src/test/java/io/jenkins/plugins/coverage/metrics/steps/CoverageChecksPublisherTest.java
Changes:
- Line coverage is now reported as consecutive line ranges.
- If a line is not covered (C0 = 0) then mutations are skipped.
- Mutator will be shown in the message of an annotation.
- Line and branch coverage annotations are skipped for mutation reports.
Fixes #775
=> Improve reporting of the GitHub checks annotations

plugin/pom.xml, plugin/src/main/java/io/jenkins/plugins/coverage/metrics/steps/CoverageRecorder.java, plugin/src/main/java/io/jenkins/plugins/coverage/metrics/steps/CoverageReportScanner.java, plugin/src/main/java/io/jenkins/plugins/coverage/metrics/steps/CoverageStep.java, plugin/src/main/java/io/jenkins/plugins/coverage/metrics/steps/CoverageTool.java, plugin/src/main/resources/io/jenkins/plugins/coverage/metrics/steps/CoverageRecorder/help-ignoreParsingErrors.html, plugin/src/main/resources/io/jenkins/plugins/coverage/metrics/steps/CoverageStep/help-ignoreParsingErrors.html, plugin/src/test/java/io/jenkins/plugins/coverage/metrics/steps/CoveragePluginITest.java, plugin/src/test/java/io/jenkins/plugins/coverage/metrics/steps/CoverageRecorderITest.java, plugin/src/test/resources/io/jenkins/plugins/coverage/metrics/steps/cobertura-duplicate-methods.xml
For more details, please see https://github.com/jenkinsci/coverage-model/pull/39.
Fixes https://github.com/jenkinsci/code-coverage-api-plugin/issues/785
=> Add a new option to ignore parser errors

plugin/src/main/java/io/jenkins/plugins/coverage/metrics/steps/CoverageBuildAction.java, plugin/src/main/resources/coverage/coverage-summary.jelly, plugin/src/test/java/io/jenkins/plugins/coverage/metrics/steps/CoverageBuildActionTest.java
The previous boolean isPostiveTrend() is changed to int getTrend() and corresponding file changes are made as per the PR - Do not use color for unchanged coverage #777
- shouldReturnPositiveTrendForLineMetric()
- shouldReturnNegativeTrendForBranchMetric()
- shouldReturnZeroForZeroDelta()
- shouldReturnZeroWhenDeltaIsNotPresent()
=> Do not use color for unchanged coverage #777
